### ISSUE TITLE
Wrong integer types when deserializing zvariant Values?

### ISSUE THREAD

**Issue by Amulet9** [3Hren/msgpack-rust#339]
Hello, I was recently trying to use msgpack to serialize data, and there seems to be an issue when deserializing [zvariant](https://docs.rs/zvariant/latest/zvariant/) values, the integer types are not correct. For example:

```rust
use zvariant::OwnedValue;

fn main() {
    let foo = Foo { data: 9001.into() };
    let serialized = rmp_serde::to_vec(&foo).expect("Failed to serialize");
    let deserialized: Foo = rmp_serde::from_slice(&serialized).expect("Failed to deserialize");
    assert_eq!(foo, deserialized)
}

#[derive(serde::Serialize, Debug, PartialEq, serde::Deserialize)]
struct Foo {
    data: OwnedValue,
}
```
with
```toml
[dependencies]
rmp-serde = "1.1.2"
serde = { version = "1.0.189", features = ["derive"] }
zvariant = "3.15.0"
```

fails to run successfully, because 
![image](https://github.com/3Hren/msgpack-rust/assets/137036112/9baa54f0-6b7b-475b-b34c-4d080c580b6c)

I am not exactly sure why this is happening, So i was wondering if someone could clue me on this.
